name: LCX
main: com.myridium.lcx.LCX_plugin
version: 0.0
authors:
  - Murdock Grewar
description: Access the Latinum Currency Exchange in-game.
commands:
  lcx:
     description: Says hello to the player.
     usage: /lcx
    